name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.10
  #firebase_core: ^1.12.0
  fluttertoast: ^8.0.8
  audioplayers: ^0.20.1
  audio_service: ^0.18.3
  intl_phone_field: ^3.0.1
  firebase_storage: ^10.2.9
  firebase_core: ^1.13.1
  file_picker: ^4.4.0
  flutter_ffmpeg: ^0.4.2
 
  path_provider: ^2.0.9
  percent_indicator: ^4.0.0
  # open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/image/pic.jpg'

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  
  assets:
    - assets/image/
    
    

